ci(check): invert build-success so it runs on failure
When a "needed" matrix job failed, the check-success job runs and fails
intentionally. When "needed" jobs were all successful, it is skipped.

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -69,12 +69,15 @@ jobs:
               --print-build-logs \
               --log-format raw
 
-  # build-success can be referenced by GitHub Rulesets
-  build-success:
+  # A meta-job that can be referenced by GitHub Rulesets.
+  # It is normally skipped, but if there was a failure it will also fail.
+  check-success:
+    name: Success
     runs-on: ubuntu-latest
+    if: failure()
     needs:
       - build
       - flake-checker
     steps:
-      - name: Done
-        run: echo Done!
+      - name: Failed
+        run: exit 1
